### ISSUE TITLE
[Middleware] Initial prototype/investigation work 

### ISSUE THREAD

**Issue by avanderhoorn** [avanderhoorn/Glimpse.Prototype#107]
Investigate how to “observe” asp.net middleware pipeline (inc. prototype and most basic UI):
- [x] Review the current Diagnostic Source messages currently in place
  - [x] Including the data which is currently being included
  - [x] Validate that the we can publish the defined Middleware messages 
  - [x] Review how names are derived for different ways that Middleware can be registered
- [ ] Publish initial messages through message bus _(prototype)_
- [ ] Validate that messages show in the client under the messages tab _(demo)_

**Comment by avanderhoorn** [comment]
This will help - https://github.com/aspnet/Diagnostics/pull/207

**Comment by avanderhoorn** [comment]
**Background:**
- Need to add service registration for `services.AddMiddlewareAnalysis();` see [here](https://github.com/aspnet/Diagnostics/blob/82e1bcf2614e42d0f33a3243e259a17fb4032ef6/samples/MiddlewareAnalysisSample/Startup.cs#L16)
- The events we are listening for are:
  - `"Microsoft.AspNet.MiddlewareAnalysis.MiddlewareStarting"` - runs before things run (args: name, httpContext)
  - `"Microsoft.AspNet.MiddlewareAnalysis.MiddlewareFinished"` - runs after things run (args: name, httpContext)
  - `"Microsoft.AspNet.MiddlewareAnalysis.MiddlewareException"` - runs after things run on exception (args: name, httpContext, exception)
  - Note, we need 
- Name of middleware is set via:
  - `app.Properties["analysis.NextMiddlewareName"] = "HomePage";` this then used by the next piece of middleware 
  - if the above doesn't provide a name then we fall back to `next.Target.GetType().FullName;`

**Tasks:**
- **2 hrs** - Update [`AnalysisMiddleware`](https://github.com/aspnet/Diagnostics/blob/dev/src/Microsoft.AspNetCore.MiddlewareAnalysis/AnalysisMiddleware.cs) so that we are getting out `id` for corrilation purposes
- **4 hrs** - Need to setup some test cases to see what type of name we get out in different circumstances
- **1 hr** - Set things up so that the [`AnalysisStartupFilter`](https://github.com/aspnet/Diagnostics/blob/dev/src/Microsoft.AspNetCore.MiddlewareAnalysis/AnalysisServiceCollectionExtensions.cs) service gets registered on behalf of Glimpse
- **2 hr** - Subscribe to DiagnosticsSource events and publish data to MessageBroker
- **4 hrs** - Setup test infrastructure around event listeners (this will serve as a pattern for other events)
- **1 hrs** - Document how users can name their middleware
